#
# Makefile include file to include standard cloudfit gitignore behaviour
# Do not include directly, is used by layer.mk, etc ...

# Custom gitignore file support
ifeq "$(CUSTOM_GITIGNORE_FILE)" ""
CLEAN_FILES+=$(topdir)/.gitignore.gen

$(topdir)/.gitignore: $(topdir)/.gitignore.gen
	cp -f $< $@

$(topdir)/.gitignore.gen: $(commontooling_dir)/misc/$(CLOUDFIT_MAKE_MODE).gitignore force_rebuild
	cp -f $< $@

	@[ ! -z "$(EXTRA_GITIGNORE_LINES)" ] && \
	echo "\n\n# Extra gitignore lines from Makefile" >> $@ && \
	set -f; for ignore_line in $(EXTRA_GITIGNORE_LINES); do \
		echo $$ignore_line >> $@ ; \
	done

check-gitignore: $(topdir)/.gitignore.gen
	@diff $< $(topdir)/.gitignore || (\
		echo "--------------------------------------------------------------------------------" && \
		echo "" && \
		echo ".gitignore is not identical to that generated by the commontooling templates." && \
		echo "" && \
		echo "Please run " && \
		echo "" && \
		echo "  make static-files" && \
		echo "" && \
		echo "and then check the new static files into git" && \
		echo "" && \
		echo "--------------------------------------------------------------------------------" && \
		exit 1); \

static-files: $(topdir)/.gitignore

check-static-files: check-gitignore

.PHONY: check-gitignore force_rebuild
endif
